name: 'Static Cloud Site - Frontend'

on:
  push:
    branches:
      - '**'
    pull_request:

jobs:
  infrastructure:
    name: 'Build/Update Infrastructure'
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: './src/terraform'

    steps:
      - name: 'actions/checkout'
        uses: actions/checkout@v1

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Format'
        run: terraform fmt -check

      - name: 'Terraform Plan'
        run: terraform plan

      - name: 'Terraform Apply'
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve

      - name: 'Set up Cloud SDK'
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Invalidate cache'
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: 'gcloud compute url-maps invalidate-cdn-cache basic-url-map --path "/*"'


