name: 'Static Cloud Site - Frontend'

on:
  push:
    branches:
      - main
    pull_request:
    
jobs:
  setup_gcloud:
    name: 'Setup gcloud'
    runs-on: ubuntu-latest
    create_credentials_file: false
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'